$primary = rgb(6796e4)
$surface = rgb(111b2d)
$secondary = rgb(6b5cd6)
$error = rgb(fd4663)
$tertiary = rgb(a666cc)
$surface_lowest = rgb(080e16)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
