$primary = rgb(f55668)
$surface = rgb(291416)
$secondary = rgb(f4843e)
$error = rgb(b00a1d)
$tertiary = rgb(f4df3e)
$surface_lowest = rgb(150a0b)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
