color0 #1b1b22
color1 #fd4663
color2 #6d73e5
color3 #a475dd
color4 #d07ed4
color5 #9397ec
color6 #bb96e9
color7 #f2f2f3
color8 #646579
color9 #fd4663
color10 #6d73e5
color11 #a475dd
color12 #d07ed4
color13 #9397ec
color14 #bb96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1b1b22
background            #1b1b22
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #24242d
active_border_color   #6d73e5
inactive_border_color #24242d
url_color             #6d73e5

active_tab_foreground   #181925
active_tab_background   #6d73e5
inactive_tab_foreground #afafb6
inactive_tab_background #24242d
cursor_trail_color      #afafb6
