monitor.alsa.rules = [

# Rename the Tangzu Wan'er (CDS.KT)
  {
    matches = [
      {
        node.description = "CDS.KT USB Audio Analog Stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "Tangzu Wan'er S.G"
      }
    }
  },

# Hide the unused NVIDIA (GA107) HDMI outputs
  {
    matches = [
      {
        node.description = "~GA107 High Definition*"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  },

# Rename the working Alder Lake Laptop Speaker
  {
    matches = [
      {
        node.description = "~Alder Lake PCH-P High Definition Audio Controller Speaker.*"
      }
    ]
    actions = {
      update-props = {
        node.description = "Speaker"
      }
    }
  },

# Hide the unused Intel (Alder Lake) HDMI outputs
  {
    matches = [
      {
        node.description = "~Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort.*"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }

# Hide the empty 3.5mm headset mic jack
  {
    matches = [
      {
        node.description = "Alder Lake PCH-P High Definition Audio Controller Stereo Microphone"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  },

# Rename the actual internal laptop microphone
  {
    matches = [
      {
        node.description = "Alder Lake PCH-P High Definition Audio Controller Digital Microphone"
      }
    ]
    actions = {
      update-props = {
        node.description = "Laptop Mic"
      }
    }
  }
  
]
